### ISSUE TITLE
Keyboard limitation on 3x1 1 knob is not true

### ISSUE THREAD

**Issue by angelosne** [kriomant/ch57x-keyboard-tool#109]
Unless I didn't understand right I will not be able to place (copy,cut,paste) on my 3 x 1 keyboard. 
But I did it and works.

layers:

  - buttons:
      # Multimedia commands are supported but
      # cannot be mixed with normal keys and modifiers.
      - ["ctrl-c", "ctrl-x", "ctrl-v"]
    knobs:
      - ccw: "volumedown"
        press: "mute"
        cw: "volumeup"

        
So maybe you can remove it from the limitations on the readme

**Comment by kriomant** [comment]
It means you cannot use "ctrl-c,volumeup" in key assignment. You can use "ctrl-c" and "volumeup" for different keys.
