### ISSUE TITLE
add function "switch layer" as key "action"

### ISSUE THREAD

**Issue by c33s** [kriomant/ch57x-keyboard-tool#111]
i am not sure this would make sense. my 2 keyboards 3x2+knob and 4x3+2knobs have no extra button to switch layer, maybe that means it cannot store multiple layers or maybe the just "saved" the extra button. if they just saved the extra button it would be nice to bind the switch layer action to a custom key.

**Comment by kriomant** [comment]
Sorry, I don't know how to switch layers programmatically.
