### ISSUE TITLE
possible to bind joy/buttons?

### ISSUE THREAD

**Issue by boldoran** [kriomant/ch57x-keyboard-tool#112]
would it be remotely possible to bind joystick buttons/inputs to a macro keyboard? ive been looking for a while and havnt found a definitive answer.
i figured i would ask here seeing you are much more knowledgeble then me.

thanks in advance

**Comment by kriomant** [comment]
https://github.com/kriomant/ch57x-keyboard-tool#how-to-do--on-key-press
