### ISSUE TITLE
Any chance of supporting this 3x2 with wheel? 

### ISSUE THREAD

**Issue by OZMattrixx** [kriomant/ch57x-keyboard-tool#114]
Purchased off TEMU and curious to see whether I might be able to get it to work on a Mac.
Thanks.

Product ID:  0xdc81
Vendor ID:  0x6d80

Speed: | Up to 12 Mb/s
Manufacturer: | SDINNOVATION

**Comment by kriomant** [comment]
It's hard to do anything without having keyboard in hands.
