### ISSUE TITLE
Confirmed working: 4 buttons

### ISSUE THREAD

**Issue by VincentSC** [kriomant/ch57x-keyboard-tool#118]
Sold on Amazon and AliExpress. Available in white and black
![image](https://github.com/user-attachments/assets/b66a99da-b0a7-4b2a-9592-97d7b5f00a06)

It can be programmed without any additional parameters:
```
rows: 1
columns: 4
knobs: 0

layers:
  - buttons:
      - ["e", "f", "g", "h"]
```

While some are sold as supporting bluetooth, I can confirm none of these do.

**Comment by mastervash** [comment]
Just an fyi, in case you'd like to update the title - the device in your image has _4 buttons_, not _4 knobs_.
