### ISSUE TITLE
Multi-layer support for macropads without a dedicated layer-switching button?

### ISSUE THREAD

**Issue by sammothxc** [kriomant/ch57x-keyboard-tool#13]
This tool is awesome and has helped me get my 3x2 +1 macro-pad working, however it seems to be defaulting to the third layer and since my macro-pad doesn't have a layer switching button, I can't seem to figure out how to utilize that feature. Is it possible to map it to one of the keys? Like setting a macro-pad specific modifier key?

[Amazon link to my model](https://www.amazon.com/dp/B0B1RDDXB5?ref=ppx_yo2ov_dt_b_product_details&th=1
)

**Comment by kriomant** [comment]
Official program doesn't have such capability. So I don't know whether this is possible. If you can find any program able to do this, we can sniff traffic and implement it.
