### ISSUE TITLE
Media Stop key

### ISSUE THREAD

**Issue by foresto** [kriomant/ch57x-keyboard-tool#14]
I notice the tool knows some media keys by name, but not the Stop key. Any chance of adding it?

I'm trying to navigate linux/X11 scan codes and key codes to figure out what number to put in angle brackets for now, but I haven't succeeded yet. It would be nice if just writing 'stop' worked.

(And by the way, thanks a lot for the tool!)

**Comment by sammothxc** [comment]
on my keyboard it seems to be 86 or 87

**Comment by kriomant** [comment]
`<183>` produces “normal key”,  while I've added media key. They are handled another way. So my fix can still help you despite same code is used.
