### ISSUE TITLE
Feature request: Keyboard shortcuts for switching layers

### ISSUE THREAD

**Issue by josepelupi** [kriomant/ch57x-keyboard-tool#15]
Great job on the project! I was having trouble using F13-F24 with the Chinese software :D. 

Is there a way to switch layers using keyboard shortcuts instead of having to manually press the layer switching button?

Thank you!

**Comment by kriomant** [comment]
Existing "official" software doesn't have such capability, so I don't know how to do it and whether it is possible at all.
