### ISSUE TITLE
Layerless keyboards:

### ISSUE THREAD

**Issue by orlando-ts** [kriomant/ch57x-keyboard-tool#17]
I have a keyboard with no layer switch and I've found a strange behaviour; when programming the keyboard the layer that will upload and work is the last one on the yaml file but upon loosing power (reconnecting the device or restarting pc) the keyboard will default to the first layer on the file for some reason. It's not really an issue, I just copied the same config on all layers but it's something that may be worth adding to the readme for some folks.

**Comment by oroehrer** [comment]
I just use one block in the config for my layerless keyboard, works fine
