### ISSUE TITLE
sequence chords not working as expected

### ISSUE THREAD

**Issue by Haycam** [kriomant/ch57x-keyboard-tool#24]
Hardware: 3 button, 1 encoder
Config file:

orientation: normal
rows: 1
columns: 3
knobs: 1
layers:
  - buttons:
      - ["ctrl-shift-m", "win-7", "win-7,ctrl-shift-m"]
    knobs:
      - ccw: 'volumedown'
        press: 'mute'
        cw: 'volumeup'

The first two keys and encoder work as expected but once I try and combine the two keystrokes it doesn't work, it performs neither win-7 which is selecting teams nor ctrl-shift-m which is putting teams on mute. 

Trying to use a keyboard event viewer gives some strange results as it never seems to send both complete commands, normally win, 7 and m and no ctl and shift.

Not 100% if what I'm trying to do is possible aka send sequential keystrokes.  I'd also love to be able to to have win-7-7 but it's an invalid combination and win-7,win-7 doesn't work.

**Comment by kriomant** [comment]
Can you show generated events?

**Comment by Haycam** [comment]
Keyboard Event viewer is a little awkward so I've highlighted the relevant keypresses.  It's doesn't show them sequentially or I can't figure out how. 

"ctrl-shift-m"
![image](https://github.com/kriomant/ch57x-keyboard-tool/assets/136435786/24bd0fc9-9ed8-4572-bfb5-f7bba77b86a2)
"win-7"
![image](https://github.com/kriomant/ch57x-keyboard-tool/assets/136435786/23bebbe5-5e44-429f-98f9-1cdca3aadd43)
"win-7,ctrl-shift-m"
![image](https://github.com/kriomant/ch57x-keyboard-tool/assets/136435786/8fd2d706-9c66-4b18-9f42-fc05d1db32ac)

**Comment by RivasMario** [comment]
Does the input you normally do require a delay?

**Comment by misterjonscott** [comment]
I wonder if this is related to my issue #49 , and it's failing because these subsquent chords are requiring a modifier keypress.  It appears some chords aren't working correctly if they're not first in the array.

**Comment by yapweiliang** [comment]
I notice that [https://github.com/rOzzy1987/MacroPad](https://github.com/rOzzy1987/MacroPad) states that the 3-button/1-knob version only stores the modifier for the first key in the sequence.  Could this be why it doesn't seem to work as expected?  I too have got the 3-button/1-knob version and seem to have the same problem.

**Comment by Haycam** [comment]
Yes that seems to be the issue

**Comment by kriomant** [comment]
Thank you, I've added note to README and verification in code.
