### ISSUE TITLE
YAML config file error

### ISSUE THREAD

**Issue by Due002** [kriomant/ch57x-keyboard-tool#25]
Hi, I'm try to config my CH57X 
for use the missing char in my keyboard layout (italy layout)
like: {  I tried to use <123> but do not print the char.

Any idea?
   

can you help me? thx :)

**Comment by Due002** [comment]
Same error with this Missin to mention my device is 3x2 with 1 knobs 

orientation: normal
rows: 2
columns: 3
knobs: 1 
layers: 
 - buttons: 
  - ["A","B","C","D","E","F"]
 - knobs: 
  - ccw: 'wheelup'
    press: 'click'
    cw: 'wheeldown'

**Comment by Due002** [comment]
I fixed by myself but now I have one more problem, 

my keyboard layout is Italian and I what use this device for type the missing char like: {  } etc but using the <123> code the devi do not print the char 

any idea?

**Comment by kriomant** [comment]
Try 'shift-leftbracket', 'shift-rightbracket'. Remember you code keys, not characters.

**Comment by Due002** [comment]
I have tried to push this combo but do not work, is possible to use the altr+shift+é (or [) or alr+123 ?

**Comment by kriomant** [comment]
Just try key combination you use to enter wanted character.
