### ISSUE TITLE
Cannot map characters "\" and "|"

### ISSUE THREAD

**Issue by gamaralf** [kriomant/ch57x-keyboard-tool#26]
If I define a layer like this:
```
layers:
  - buttons:
      - ["|", "a", "b"]
 ```

I get the error:
 ```
$ ./ch57x-keyboard-tool validate < mapping.yml
Error: load mapping config

Caused by:
    layers[0].buttons[0][0]: error Alpha at: | at line 24 column 10
 ```

It is that same thing with "\\". It does not matter how I try to escape them, I still get the error.

**Comment by kriomant** [comment]
It's because you should specify pressed keys, not characters.
To get "\" use "backslash", to get "|" — "shift-backslash".
Use `show-keys` command to get all supported keys.
