### ISSUE TITLE
[RFE] Add the ability to add a delay

### ISSUE THREAD

**Issue by e-minguez** [kriomant/ch57x-keyboard-tool#27]
I've setup one of my keys to lock the screen as `'cmd-ctrl-q'` but I usually like to lock the screen and suspend it, so I need to press escape after that. It would be nice to add a "delay" so the 'cmd-ctrl-q<>escape' shortcut works.

I don't think such delay can be implemented tho, but just in case :)

Thanks!

**Comment by kriomant** [comment]
> I don't think such delay can be implemented tho

You are right, I'm limited by what hardware can do and what "official" software can. If you find any software which can do it, I'll copy it. Otherwise let's think it's impossible.
