### ISSUE TITLE
Problems to execute ch57x-keyboard-tool on Mac

### ISSUE THREAD

**Issue by janstieler** [kriomant/ch57x-keyboard-tool#32]
Hi,
on Mac I go inside the folder and run ch57x-keyboard-tool validate < ch57-mapping.yaml.
I got the error `zsh: command not found: ch57x-keyboard-tool`. What do I'm wrong?

Cheers

**Comment by kriomant** [comment]
Try `./ch57x-keyboard-tool validate < ch57-mapping.yaml`

**Comment by janstieler** [comment]
Hi,
thank you. i tried `. ch57x-keyboard-tool validate < ch57-mapping.yaml` and not `./ch57x-keyboard-tool validate < ch57-mapping.yaml`. Thats if you not running tools mostly on terminal :) .

And I got the error `dyld: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib` but 
`brew install libusb ` solve the problem.

Cheers
