### ISSUE TITLE
small issue for horizontal / vertical 

### ISSUE THREAD

**Issue by creeras** [kriomant/ch57x-keyboard-tool#34]
I have 3*3 keys + 2 knobs one 
with translucent top cover and black bottom case,
with no LED chips on board,
with BT connection. 
 
It works vertical position as default. 

knob1  - knob2
key1 key2 key3
key4 key5 key6
key7 key8 key9

so, should use "clockwise" option for horizontal position.  
It was same as seller's program too. 

In windows 11, 
"ch57x-keyboard-tool" works perfectly for now. 

I hope that the 5-character sequence delimitation and time delay input supported by the new hardware version will be possible in this model, but it probably won't be possible.

**Comment by kriomant** [comment]
Sorry, I haven't caught what the small issue is )
