### ISSUE TITLE
Can't have multiple actions on knobs, need faster scroll

### ISSUE THREAD

**Issue by nkiest** [kriomant/ch57x-keyboard-tool#36]
'wheelup' is far too slow scrolling for my taste. But if I change it in the OS, my other devices go rocket powered.
So I tried "wheelup,wheelup,wheelup" to try making it go faster, but tool reports "error Eof at: ,wheelup,wheelup"
Is there any way to make it scroll faster?

**Comment by pedjas** [comment]
I have the same issue. Knob is to slow. 

To turn up volume form 0 to 100% it needs to be rotated four full circles. I would like to make do it in less than a circle.

I hope that is possible to set.

**Comment by kriomant** [comment]
I tried various ways to change wheel delta with no success.

Proposed workaround is to assign some rare shortcut to knob and then use external software to map this shortcut to wheel events.
