### ISSUE TITLE
Sudo/Root

### ISSUE THREAD

**Issue by PeterPaul1234** [kriomant/ch57x-keyboard-tool#37]
Hello,
some would find it helpful to know that under some Linux distro the uploading of this script only works running as root/sudo.
Greets

**Comment by kriomant** [comment]
Can you please name the distro and who error you get when run program without sudo?

**Comment by lucaspolo** [comment]
Hi @kriomant, here in my installation the error is:

```
$ ch57x-keyboard-tool upload < teste.yaml 
Error: open USB device

Caused by:
    Access denied (insufficient permissions)
```

Running Ubuntu 22.04.

**Comment by jfisbein** [comment]
Had same error on Ubuntu 22.04
```
./ch57x-keyboard-tool upload < example-mapping.yaml                                                                                                               2 ↵  13:25:30 
Error: open USB device

Caused by:
    Access denied (insufficient permissions)
```
Simply adding `sudo` before the command worked like a charm. Thanks you very much for this tool!
