### ISSUE TITLE
Key Combinations

### ISSUE THREAD

**Issue by thre3eye** [kriomant/ch57x-keyboard-tool#39]
Hi - thanks very much for the tool!

I am now trying to define a key combination. i.e. a key as 'Ctrl' and the knob as 'left' and 'right' (or ideally pushing the knob is 'Ctrl' combined with turning 'left', 'right') Is it not possible with this hardware to send combined signals from 2 switches? Alternatively, is there a trick to 'toggle' mod keys, such as 'Ctrl'? Unfortunately my device doesn't have a layer switch, that would be another workaround... Thanks.

**Comment by kriomant** [comment]
Unfortunately, it doesn't work. I wanted it too. 
One possible way to do some tricky combinations (and also application-specific shortcuts) is to assign some rarely used combinations to keyboard keys and then map them to needed behaviour using programs like BetterTouchTool or Karabiner.
