### ISSUE TITLE
Add support horizontal mouse wheel

### ISSUE THREAD

**Issue by caffeine-mgn** [kriomant/ch57x-keyboard-tool#4]
Can you add support of horizontal mouse wheel? It very usable for some programs like gimp.

**Comment by kriomant** [comment]
Try to use 'shift-wheelup' / 'shift-wheeldown'.

**Comment by caffeine-mgn** [comment]
It work as workaround in some apps like browsers

**Comment by kriomant** [comment]
Does it work for gimp?

**Comment by sammothxc** [comment]
Confirmed this works system-wide in Ubuntu, including gimp

**Comment by kriomant** [comment]
Ok, then closing it for now.
