### ISSUE TITLE
M1 Pro steps 

### ISSUE THREAD

**Issue by cguldogan** [kriomant/ch57x-keyboard-tool#40]
Hi, 

Thanks for the keyboard tool, 

I have 3 buttons 1 row 1 knob version.  I managed to use the tool like below. 

0- I installed Rust `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
1- I downloaded the latest code. 
2- I did `brew install libusb `
3- Upgraded dependencies with `cargo update` 
4- Then I modified the yml as suggested 
5- Installed with `cargo install ch57x-keyboard-tool`
6- Final step `ch57x-keyboard-tool upload < example-mapping.yaml`

It worked like a charm, I have no Rust knowledge thanks @kriomant and other authors. 

I think there is a piece of good information in this repo, Is there a blog post about it?

**Comment by kriomant** [comment]
Now universal binary for Mac is built.
