### ISSUE TITLE
Problem to find libusb path

### ISSUE THREAD

**Issue by juliobrs** [kriomant/ch57x-keyboard-tool#41]
Hi, on Mac (M1) I've done "brew install libusb" and it is installed, but when I try to run the command I get this:

./ch57x-keyboard-tool led 1
dyld[85740]: **Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib**

  Referenced from: <007FA9B3-0278-385D-A5D6-DB4F0F08B041> /Users/XXXXXX/Downloads/ch57x-keyboard-tool-x86_64-apple-darwin/ch57x-keyboard-tool
  Reason: tried: '/usr/local/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/usr/local/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/usr/local/lib/libusb-1.0.0.dylib' (no such file), '/usr/lib/libusb-1.0.0.dylib' (no such file, not in dyld cache)
Abort trap: 6

Same error as for trying to validate it. Any idea of what I'm doing wrong? Thanks!

**Comment by kriomant** [comment]
Now universal binary is built, you can find it in releases.
