### ISSUE TITLE
Can't get it to run on Windows 10

### ISSUE THREAD

**Issue by xbonet** [kriomant/ch57x-keyboard-tool#42]
I click on the executable and a window opens for a brief instant and then closes. Have tried downloading previous versions, it's the same. I made sure to install UsbDk. I'm assuming this tool has a GUI as per the comment that the original software "is very ugly and inconvenient". Am I wrong? Should I be running it in CMD? Please advise.

**Comment by pedjas** [comment]
It runs in command line. No GUI.
Open command window and type 

`ch57x-keyboard-tool.exe<enter>`

That will show you help.
