### ISSUE TITLE
FYI: USB-C-to-C cables do not work

### ISSUE THREAD

**Issue by VincentSC** [kriomant/ch57x-keyboard-tool#44]
This is for those who see a way to get their "12 key 2 knobs macro keyboard" working, but find that USB does not connect when using a USB-C-to-C cable. This is for you! ;)

I almost wanted to return it, as it did not show up under the USB-devices on my Macbook (only USB-C ports). The same cable could connect to my Android-phone, so the cable was functioning. Then I tried my old Linux-laptop with the provided cable, and then suddenly the orange LED on the keyboard turned on! I tried the same USB-C cable on that laptop and it neither worked. This means that the keyboard does have a USB-C connection, but that's just the wiring, and is "old" USB-A/B under the hood.

In the end I got it to work with a USB-hub.

**Comment by kriomant** [comment]
Thank you for information!
