### ISSUE TITLE
Issues when using 12 key, 3 knob device with Powershell on Windows 11.

### ISSUE THREAD

**Issue by DermotBohan** [kriomant/ch57x-keyboard-tool#51]
Hi, thanks for the code. Sharing experience as a newbie coder.

Some issues I've found when using the device with the specs in title:

COMMANDS
.\ch57x-keyboard-tool.exe upload < '.\your-config.yaml'
This command causes the program to hang.

start-process .\ch57x-keyboard-tool.exe upload -RedirectStandardInput '.\your-config.yaml'
This command runs successfully.

.\ch57x-keyboard-tool.exe upload -RedirectStandardInput '.\your-config.yaml'
This command returns the errror:  Found argument '-R' which wasn't expected, or isn't valid in this context

CONFIG
orientation: normal
orientation: upsidedown
These work as expected

orientation: clockwise
orientation: counterclockwise
These do not work and the configuration stays the same as whatever the previous config was.

Thanks.

![image](https://github.com/kriomant/ch57x-keyboard-tool/assets/18267075/95fe055a-ac3e-493d-8710-4f28057ee222)

**Comment by kriomant** [comment]
Thank you. I've added note about using with PowerShell to README.

About "These do not work", I need exact error help.
