### ISSUE TITLE
Associate the execution of a program/script with a specific button press

### ISSUE THREAD

**Issue by GHenry21** [kriomant/ch57x-keyboard-tool#55]
Add the function to map a specific button to run a program/script in order to map homeassistant script via api

**Comment by kriomant** [comment]
This tool does not handle key presses by itself. All it does it writes bindings to keyboard and then exists. Keyboard itself cannot run scripts. While I can add such functionality to this tool, I don't think it's a good idea. There are plenty of automation tools already.

What I offer you to do:
1. Assing some strange key combination you don't usually use, e.g. alt-shift-ctrl-1
2. Use third-party software, like BetterTouchTool or any other, to do any action when this key combination is pressed
3. Done
