### ISSUE TITLE
Actions on mac

### ISSUE THREAD

**Issue by vinschi** [kriomant/ch57x-keyboard-tool#56]
Hi, first thanks for this, I was finally able to configure the 3x1 bought on AliExpress, taking dust on my desk :)

Some of the actions are not working on Mac (for example, printscreen doesn't work but the workaround is pretty easy; I used the shortcut and it works as expected, calculator doesn't do anything though). Maybe you can print the ones available on windows and the ones available on other OS since you offer the tool for than one operative system.

I have two questions for you:

1. is it possible to configure more than one action for each button? I'm not sure if I didn't understand how to configure it from the small documentation, or if it's not possible at all, but imagine something like you quickly press is one action, and if you long press is another one. Right now, I have 2 buttons used only for copy and paste, but maybe there is a better way to use only one button for that.
2. right now, the configuration is applied to any window; is there any chance it could be smarter so that will change the action to the button accordingly? Imagine I'm watching a video then the buttons are media control, I'm in a video call app and the buttons could be something else like mute or leave the call. I guess this cheap macropad is not that smart, but maybe you have a way to fix it.

Anyway, thanks a lot for your work!

**Comment by kriomant** [comment]
This tool is all about programming keyboard: which keys to emulate when physical key is pressed.

Your questions are about reacting to these keys being pressed. There are other programs for that, like Karabiner or BetterTouchTool. Read https://github.com/kriomant/ch57x-keyboard-tool#automation
And yes, you can create per-app actions too.
