### ISSUE TITLE
Read configuration from device

### ISSUE THREAD

**Issue by kamaaina** [kriomant/ch57x-keyboard-tool#65]
Sorry for the cross post, as I had initially created this in the Discussions area, but github doesn't show a number indicating there is an ongoing Discussion which perhaps might not get seen by others would could provide feedback so am posting it here.

It is more of an enhancement / feature request.

Please see this [Configuration Request](https://github.com/kriomant/ch57x-keyboard-tool/discussions/64)

**Comment by kriomant** [comment]
I don't know direct way to do this.
It is possible to ask user to press each button in sequence and see which keyboard events are generated, but it's not very robust.
