### ISSUE TITLE
When you assign two keys to one button

### ISSUE THREAD

**Issue by high37806** [kriomant/ch57x-keyboard-tool#71]
When allocating two keys to one button, I want to make sure that the assigned two keys are pressed long at the same time, but when you allocate two keys using ',', each key is only pressed short once. Can't you make other keys enter long at the same time like shift key or ctrl key? I'm sorry if it's hard to understand because I used a translator.

**Comment by kriomant** [comment]
Show your config

**Comment by high37806** [comment]
I'd like to assign two direction keys to one button.
