### ISSUE TITLE
Long press not working

### ISSUE THREAD

**Issue by munzirstudio** [kriomant/ch57x-keyboard-tool#75]
Hi im using the default device 3x4. Seems the long press to continuously insert a key is not working, it only allows you to insert per key press. Any possibility to enable this?

**Comment by kriomant** [comment]
Hello. It is not responsibility of this program. There is no known ways to change this behaviour.
If you are on MacOS, maybe you need smth like [this](https://www.howtogeek.com/267463/how-to-enable-key-repeating-in-macos/).
