### ISSUE TITLE
Request: Allow HID keyboard scan codes

### ISSUE THREAD

**Issue by orlando-ts** [kriomant/ch57x-keyboard-tool#8]
Could it be made to manually wire the scan code on the .yml file to program any key I want?

I'm looking to program every single thing on the keyboard with obscure and unused keys so that I can rebind with AutoHotkey depending on what app I'm on. I used F13+ but still missing the rotary encoders (6 keys).

**Comment by kriomant** [comment]
Fixed in 1.1, use like this: "shift-<20>".
