### ISSUE TITLE
3x4 keys with 3 knobs works

### ISSUE THREAD

**Issue by neuralnermal** [kriomant/ch57x-keyboard-tool#81]
I didn't see it in the supported devices. Can confirm it works
This is the macro pad I'm using: https://aliexpress.com/item/1005006353228764.html

**Comment by hoshy42** [comment]
Hi neuralnermal,
how did you make it work?
Mine is recognized as device id 514c:8842 
And the tool wont program it... "invalid digit found in string"
thanks
