### ISSUE TITLE
"Found argument ..... isnt valid."

### ISSUE THREAD

**Issue by tototat** [kriomant/ch57x-keyboard-tool#84]
I know this is a newbie question but I'm having an issue with windows power shell command returning "error: Found argument 'example-mapping.yaml' which wasn't expected, or isn't valid in this context" ( I'm using the default mapping with no alteration.) other commands such as help or show-keys work perfectly.

the command I wrote is 

./ch57x-keyboard-tool upload example-mapping.yaml

(if i remove the ./ in beggining it returns .... not recognized the name of a cmdlet....)
also im in the same directory as the extracted files location.

**Comment by kriomant** [comment]
Correct command is given in README: https://github.com/kriomant/ch57x-keyboard-tool/blob/master/README.md#windows--powershell

But future versions of tool will accept file name to simplify usage.
