### ISSUE TITLE
Alternative software

### ISSUE THREAD

**Issue by erdesigns-eu** [kriomant/ch57x-keyboard-tool#87]
First beta release of my own software for the macro keyboard. Only for windows but with a GUI. I made it for a 3x4 keys and 3 knobs keypad, i dont want to "hijack" users from this repository - just want to provide an alternative with a GUI.

https://github.com/erdesigns-eu/HID-Macro-Keyboard

**Comment by jclulow** [comment]
**Fair warning: the executable linked from this "alternative software" is flagged by Windows Detector as containing a virus.**

**Comment by erdesigns-eu** [comment]
Thanks for noticing, reuploaded - and scanned on virustotal. Also excuses for posting this here, wasnt meant to post this in here but somewhere else .. maybe the owner can delete this post thanks.
